[build]
  command = "npm run build"
  publish = ".next"
  base = "."

[dev]
  command = "npm run dev"
  port = 8888

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
