[build]
 command = "npm run build"
 publish = "dashboard-next/.next"
 base = "dashboard-next"

[dev]
 command = "npm run dev"
 port = 8888

[functions]
 directory = "netlify/functions"

[build.environment]
 NODE_VERSION = "18"
